// $begin{copyright}
//
// This file is part of WebSharper
//
// Copyright (c) 2008-2014 IntelliFactory
//
// Licensed under the Apache License, Version 2.0 (the "License"); you
// may not use this file except in compliance with the License.  You may
// obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.  See the License for the specific language governing
// permissions and limitations under the License.
//
// $end{copyright}

namespace IntelliFactory.WebSharper.UI.Next

open IntelliFactory.WebSharper

/// This is an auto-generated module providing HTML5 vocabulary.
/// See tools/ElemScraper.fsx for the code-generation logic.
[<JavaScript>]
module Html =

    /// HTML5 element functions.
    module Elements =

        // <Element>
        let A ats ch = Doc.Element "a" ats ch
        let Abbr ats ch = Doc.Element "abbr" ats ch
        let Address ats ch = Doc.Element "address" ats ch
        let Area ats ch = Doc.Element "area" ats ch
        let Article ats ch = Doc.Element "article" ats ch
        let Aside ats ch = Doc.Element "aside" ats ch
        let Audio ats ch = Doc.Element "audio" ats ch
        let B ats ch = Doc.Element "b" ats ch
        let Base ats ch = Doc.Element "base" ats ch
        let BDI ats ch = Doc.Element "bdi" ats ch
        let BDO ats ch = Doc.Element "bdo" ats ch
        let BlockQuote ats ch = Doc.Element "blockquote" ats ch
        let Body ats ch = Doc.Element "body" ats ch
        let Br ats ch = Doc.Element "br" ats ch
        let Button ats ch = Doc.Element "button" ats ch
        let Canvas ats ch = Doc.Element "canvas" ats ch
        let Caption ats ch = Doc.Element "caption" ats ch
        let Cite ats ch = Doc.Element "cite" ats ch
        let Code ats ch = Doc.Element "code" ats ch
        let Col ats ch = Doc.Element "col" ats ch
        let ColGroup ats ch = Doc.Element "colgroup" ats ch
        let Data ats ch = Doc.Element "data" ats ch
        let DataList ats ch = Doc.Element "datalist" ats ch
        let DD ats ch = Doc.Element "dd" ats ch
        let Del ats ch = Doc.Element "del" ats ch
        let Details ats ch = Doc.Element "details" ats ch
        let DFN ats ch = Doc.Element "dfn" ats ch
        let Div ats ch = Doc.Element "div" ats ch
        let DL ats ch = Doc.Element "dl" ats ch
        let DT ats ch = Doc.Element "dt" ats ch
        let Em ats ch = Doc.Element "em" ats ch
        let Embed ats ch = Doc.Element "embed" ats ch
        let FieldSet ats ch = Doc.Element "fieldset" ats ch
        let FigCaption ats ch = Doc.Element "figcaption" ats ch
        let Figure ats ch = Doc.Element "figure" ats ch
        let Footer ats ch = Doc.Element "footer" ats ch
        let Form ats ch = Doc.Element "form" ats ch
        let H1 ats ch = Doc.Element "h1" ats ch
        let H2 ats ch = Doc.Element "h2" ats ch
        let H3 ats ch = Doc.Element "h3" ats ch
        let H4 ats ch = Doc.Element "h4" ats ch
        let H5 ats ch = Doc.Element "h5" ats ch
        let H6 ats ch = Doc.Element "h6" ats ch
        let Head ats ch = Doc.Element "head" ats ch
        let Header ats ch = Doc.Element "header" ats ch
        let HR ats ch = Doc.Element "hr" ats ch
        let Html ats ch = Doc.Element "html" ats ch
        let I ats ch = Doc.Element "i" ats ch
        let IFrame ats ch = Doc.Element "iframe" ats ch
        let Img ats ch = Doc.Element "img" ats ch
        let Input ats ch = Doc.Element "input" ats ch
        let Ins ats ch = Doc.Element "ins" ats ch
        let Kbd ats ch = Doc.Element "kbd" ats ch
        let Keygen ats ch = Doc.Element "keygen" ats ch
        let Label ats ch = Doc.Element "label" ats ch
        let Legend ats ch = Doc.Element "legend" ats ch
        let LI ats ch = Doc.Element "li" ats ch
        let Link ats ch = Doc.Element "link" ats ch
        let Main ats ch = Doc.Element "main" ats ch
        let Map ats ch = Doc.Element "map" ats ch
        let Mark ats ch = Doc.Element "mark" ats ch
        let Menu ats ch = Doc.Element "menu" ats ch
        let MenuItem ats ch = Doc.Element "menuitem" ats ch
        let Meta ats ch = Doc.Element "meta" ats ch
        let Meter ats ch = Doc.Element "meter" ats ch
        let Nav ats ch = Doc.Element "nav" ats ch
        let NoScript ats ch = Doc.Element "noscript" ats ch
        let Object ats ch = Doc.Element "object" ats ch
        let OL ats ch = Doc.Element "ol" ats ch
        let OptGroup ats ch = Doc.Element "optgroup" ats ch
        let Option ats ch = Doc.Element "option" ats ch
        let Output ats ch = Doc.Element "output" ats ch
        let P ats ch = Doc.Element "p" ats ch
        let Param ats ch = Doc.Element "param" ats ch
        let Picture ats ch = Doc.Element "picture" ats ch
        let Pre ats ch = Doc.Element "pre" ats ch
        let Progress ats ch = Doc.Element "progress" ats ch
        let Q ats ch = Doc.Element "q" ats ch
        let RP ats ch = Doc.Element "rp" ats ch
        let RT ats ch = Doc.Element "rt" ats ch
        let Ruby ats ch = Doc.Element "ruby" ats ch
        let S ats ch = Doc.Element "s" ats ch
        let Samp ats ch = Doc.Element "samp" ats ch
        let Script ats ch = Doc.Element "script" ats ch
        let Section ats ch = Doc.Element "section" ats ch
        let Select ats ch = Doc.Element "select" ats ch
        let Small ats ch = Doc.Element "small" ats ch
        let Source ats ch = Doc.Element "source" ats ch
        let Span ats ch = Doc.Element "span" ats ch
        let Strong ats ch = Doc.Element "strong" ats ch
        let Style ats ch = Doc.Element "style" ats ch
        let Sub ats ch = Doc.Element "sub" ats ch
        let Summary ats ch = Doc.Element "summary" ats ch
        let Sup ats ch = Doc.Element "sup" ats ch
        let Table ats ch = Doc.Element "table" ats ch
        let TBody ats ch = Doc.Element "tbody" ats ch
        let TD ats ch = Doc.Element "td" ats ch
        let TextArea ats ch = Doc.Element "textarea" ats ch
        let TFoot ats ch = Doc.Element "tfoot" ats ch
        let TH ats ch = Doc.Element "th" ats ch
        let THead ats ch = Doc.Element "thead" ats ch
        let Time ats ch = Doc.Element "time" ats ch
        let Title ats ch = Doc.Element "title" ats ch
        let TR ats ch = Doc.Element "tr" ats ch
        let Track ats ch = Doc.Element "track" ats ch
        let U ats ch = Doc.Element "u" ats ch
        let UL ats ch = Doc.Element "ul" ats ch
        let Var ats ch = Doc.Element "var" ats ch
        let Video ats ch = Doc.Element "video" ats ch
        let WBR ats ch = Doc.Element "wbr" ats ch
        // </Element>

    /// HTML attributes.
    module Attributes =

        // <Attr>
        let Accept = "accept"
        let AcceptCharset = "accept-charset"
        let Accesskey = "accesskey"
        let Action = "action"
        let Align = "align"
        let Alt = "alt"
        let Async = "async"
        let AutoComplete = "autocomplete"
        let AutoFocus = "autofocus"
        let AutoPlay = "autoplay"
        let AutoSave = "autosave"
        let BgColor = "bgcolor"
        let Border = "border"
        let Buffered = "buffered"
        let Challenge = "challenge"
        let Charset = "charset"
        let Checked = "checked"
        let Cite = "cite"
        let Class = "class"
        let Code = "code"
        let Codebase = "codebase"
        let Color = "color"
        let Cols = "cols"
        let ColSpan = "colspan"
        let Content = "content"
        let ContentEditable = "contenteditable"
        let ContextMenu = "contextmenu"
        let Controls = "controls"
        let Coords = "coords"
        let Datetime = "datetime"
        let Default = "default"
        let Defer = "defer"
        let Dir = "dir"
        let DirName = "dirname"
        let Disabled = "disabled"
        let Download = "download"
        let Draggable = "draggable"
        let Dropzone = "dropzone"
        let EncType = "enctype"
        let For = "for"
        let Form = "form"
        let FormAction = "formaction"
        let Headers = "headers"
        let Height = "height"
        let Hidden = "hidden"
        let High = "high"
        let Href = "href"
        let HrefLang = "hreflang"
        let HttpEquiv = "http-equiv"
        let Icon = "icon"
        let ID = "id"
        let IsMap = "ismap"
        let ItemProp = "itemprop"
        let KeyType = "keytype"
        let Kind = "kind"
        let Label = "label"
        let Lang = "lang"
        let Language = "language"
        let List = "list"
        let Loop = "loop"
        let Low = "low"
        let Manifest = "manifest"
        let Max = "max"
        let MaxLength = "maxlength"
        let Media = "media"
        let Method = "method"
        let Min = "min"
        let Multiple = "multiple"
        let Name = "name"
        let NoValidate = "novalidate"
        let Open = "open"
        let Optimum = "optimum"
        let Pattern = "pattern"
        let Ping = "ping"
        let Placeholder = "placeholder"
        let Poster = "poster"
        let Preload = "preload"
        let PubDate = "pubdate"
        let RadioGroup = "radiogroup"
        let Readonly = "readonly"
        let Rel = "rel"
        let Required = "required"
        let Reversed = "reversed"
        let Rows = "rows"
        let RowSpan = "rowspan"
        let Sandbox = "sandbox"
        let Spellcheck = "spellcheck"
        let Scope = "scope"
        let Scoped = "scoped"
        let Seamless = "seamless"
        let Selected = "selected"
        let Shape = "shape"
        let Size = "size"
        let Sizes = "sizes"
        let Span = "span"
        let Src = "src"
        let Srcdoc = "srcdoc"
        let SrcLang = "srclang"
        let Start = "start"
        let Step = "step"
        let Style = "style"
        let Summary = "summary"
        let TabIndex = "tabindex"
        let Target = "target"
        let Title = "title"
        let Type = "type"
        let Usemap = "usemap"
        let Value = "value"
        let Width = "width"
        let Wrap = "wrap"
        // </Attr>

    /// SVG elements.
    module SvgElements =

        // <SVG>
        let A ats ch = Doc.SvgElement "a" ats ch
        let AltGlyph ats ch = Doc.SvgElement "altglyph" ats ch
        let AltGlyphDef ats ch = Doc.SvgElement "altglyphdef" ats ch
        let AltGlyphItem ats ch = Doc.SvgElement "altglyphitem" ats ch
        let Animate ats ch = Doc.SvgElement "animate" ats ch
        let AnimateColor ats ch = Doc.SvgElement "animatecolor" ats ch
        let AnimateMotion ats ch = Doc.SvgElement "animatemotion" ats ch
        let AnimateTransform ats ch = Doc.SvgElement "animatetransform" ats ch
        let Circle ats ch = Doc.SvgElement "circle" ats ch
        let ClipPath ats ch = Doc.SvgElement "clippath" ats ch
        let ColorProfile ats ch = Doc.SvgElement "color-profile" ats ch
        let Cursor ats ch = Doc.SvgElement "cursor" ats ch
        let Defs ats ch = Doc.SvgElement "defs" ats ch
        let Desc ats ch = Doc.SvgElement "desc" ats ch
        let Ellipse ats ch = Doc.SvgElement "ellipse" ats ch
        let FeBlend ats ch = Doc.SvgElement "feblend" ats ch
        let FeColorMatrix ats ch = Doc.SvgElement "fecolormatrix" ats ch
        let FeComponentTransfer ats ch = Doc.SvgElement "fecomponenttransfer" ats ch
        let FeComposite ats ch = Doc.SvgElement "fecomposite" ats ch
        let FeConvolveMatrix ats ch = Doc.SvgElement "feconvolvematrix" ats ch
        let FeDiffuseLighting ats ch = Doc.SvgElement "fediffuselighting" ats ch
        let FeDisplacementMap ats ch = Doc.SvgElement "fedisplacementmap" ats ch
        let FeDistantLight ats ch = Doc.SvgElement "fedistantlight" ats ch
        let FeFlood ats ch = Doc.SvgElement "feflood" ats ch
        let FeFuncA ats ch = Doc.SvgElement "fefunca" ats ch
        let FeFuncB ats ch = Doc.SvgElement "fefuncb" ats ch
        let FeFuncG ats ch = Doc.SvgElement "fefuncg" ats ch
        let FeFuncR ats ch = Doc.SvgElement "fefuncr" ats ch
        let FeGaussianBlur ats ch = Doc.SvgElement "fegaussianblur" ats ch
        let FeImage ats ch = Doc.SvgElement "feimage" ats ch
        let FeMerge ats ch = Doc.SvgElement "femerge" ats ch
        let FeMergeNode ats ch = Doc.SvgElement "femergenode" ats ch
        let FeMorphology ats ch = Doc.SvgElement "femorphology" ats ch
        let FeOffset ats ch = Doc.SvgElement "feoffset" ats ch
        let FePointLight ats ch = Doc.SvgElement "fepointlight" ats ch
        let FeSpecularLighting ats ch = Doc.SvgElement "fespecularlighting" ats ch
        let FeSpotLight ats ch = Doc.SvgElement "fespotlight" ats ch
        let FeTile ats ch = Doc.SvgElement "fetile" ats ch
        let FeTurbulence ats ch = Doc.SvgElement "feturbulence" ats ch
        let Filter ats ch = Doc.SvgElement "filter" ats ch
        let Font ats ch = Doc.SvgElement "font" ats ch
        let FontFace ats ch = Doc.SvgElement "font-face" ats ch
        let FontFaceFormat ats ch = Doc.SvgElement "font-face-format" ats ch
        let FontFaceName ats ch = Doc.SvgElement "font-face-name" ats ch
        let FontFaceSrc ats ch = Doc.SvgElement "font-face-src" ats ch
        let FontFaceUri ats ch = Doc.SvgElement "font-face-uri" ats ch
        let ForeignObject ats ch = Doc.SvgElement "foreignobject" ats ch
        let G ats ch = Doc.SvgElement "g" ats ch
        let Glyph ats ch = Doc.SvgElement "glyph" ats ch
        let GlyphRef ats ch = Doc.SvgElement "glyphref" ats ch
        let HKern ats ch = Doc.SvgElement "hkern" ats ch
        let Image ats ch = Doc.SvgElement "image" ats ch
        let Line ats ch = Doc.SvgElement "line" ats ch
        let LinearGradient ats ch = Doc.SvgElement "lineargradient" ats ch
        let Marker ats ch = Doc.SvgElement "marker" ats ch
        let Mask ats ch = Doc.SvgElement "mask" ats ch
        let Metadata ats ch = Doc.SvgElement "metadata" ats ch
        let MissingGlyph ats ch = Doc.SvgElement "missing-glyph" ats ch
        let MPath ats ch = Doc.SvgElement "mpath" ats ch
        let Path ats ch = Doc.SvgElement "path" ats ch
        let Pattern ats ch = Doc.SvgElement "pattern" ats ch
        let Polygon ats ch = Doc.SvgElement "polygon" ats ch
        let Polyline ats ch = Doc.SvgElement "polyline" ats ch
        let RadialGradient ats ch = Doc.SvgElement "radialgradient" ats ch
        let Rect ats ch = Doc.SvgElement "rect" ats ch
        let Script ats ch = Doc.SvgElement "script" ats ch
        let Set ats ch = Doc.SvgElement "set" ats ch
        let Stop ats ch = Doc.SvgElement "stop" ats ch
        let Style ats ch = Doc.SvgElement "style" ats ch
        let Svg ats ch = Doc.SvgElement "svg" ats ch
        let Switch ats ch = Doc.SvgElement "switch" ats ch
        let Symbol ats ch = Doc.SvgElement "symbol" ats ch
        let Text ats ch = Doc.SvgElement "text" ats ch
        let TextPath ats ch = Doc.SvgElement "textpath" ats ch
        let Title ats ch = Doc.SvgElement "title" ats ch
        let TRef ats ch = Doc.SvgElement "tref" ats ch
        let TSpan ats ch = Doc.SvgElement "tspan" ats ch
        let Use ats ch = Doc.SvgElement "use" ats ch
        let View ats ch = Doc.SvgElement "view" ats ch
        let VKern ats ch = Doc.SvgElement "vkern" ats ch
        // </SVG>

    /// SVG attributes.
    module SvgAttributes =

        // <SVGA>
        let AccentHeight = "accent-height"
        let Accumulate = "accumulate"
        let Additive = "additive"
        let AlignmentBaseline = "alignment-baseline"
        let Ascent = "ascent"
        let AttributeName = "attributeName"
        let AttributeType = "attributeType"
        let Azimuth = "azimuth"
        let BaseFrequency = "baseFrequency"
        let BaselineShift = "baseline-shift"
        let Begin = "begin"
        let Bias = "bias"
        let CalcMode = "calcMode"
        let Class = "class"
        let Clip = "clip"
        let ClipPathUnits = "clipPathUnits"
        let ClipPath = "clip-path"
        let ClipRule = "clip-rule"
        let Color = "color"
        let ColorInterpolation = "color-interpolation"
        let ColorInterpolationFilters = "color-interpolation-filters"
        let ColorProfile = "color-profile"
        let ColorRendering = "color-rendering"
        let ContentScriptType = "contentScriptType"
        let ContentStyleType = "contentStyleType"
        let Cursor = "cursor"
        let CX = "cx"
        let CY = "cy"
        let D = "d"
        let DiffuseConstant = "diffuseConstant"
        let Direction = "direction"
        let Display = "display"
        let Divisor = "divisor"
        let DominantBaseline = "dominant-baseline"
        let Dur = "dur"
        let DX = "dx"
        let DY = "dy"
        let EdgeMode = "edgeMode"
        let Elevation = "elevation"
        let End = "end"
        let ExternalResourcesRequired = "externalResourcesRequired"
        let Fill = "fill"
        let FillOpacity = "fill-opacity"
        let FillRule = "fill-rule"
        let Filter = "filter"
        let FilterRes = "filterRes"
        let FilterUnits = "filterUnits"
        let FloodColor = "flood-color"
        let FloodOpacity = "flood-opacity"
        let FontFamily = "font-family"
        let FontSize = "font-size"
        let FontSizeAdjust = "font-size-adjust"
        let FontStretch = "font-stretch"
        let FontStyle = "font-style"
        let FontVariant = "font-variant"
        let FontWeight = "font-weight"
        let From = "from"
        let GradientTransform = "gradientTransform"
        let GradientUnits = "gradientUnits"
        let Height = "height"
        let ImageRendering = "image-rendering"
        let IN = "in"
        let In2 = "in2"
        let K1 = "k1"
        let K2 = "k2"
        let K3 = "k3"
        let K4 = "k4"
        let KernelMatrix = "kernelMatrix"
        let KernelUnitLength = "kernelUnitLength"
        let Kerning = "kerning"
        let KeySplines = "keySplines"
        let KeyTimes = "keyTimes"
        let LetterSpacing = "letter-spacing"
        let LightingColor = "lighting-color"
        let LimitingConeAngle = "limitingConeAngle"
        let Local = "local"
        let MarkerEnd = "marker-end"
        let MarkerMid = "marker-mid"
        let MarkerStart = "marker-start"
        let MarkerHeight = "markerHeight"
        let MarkerUnits = "markerUnits"
        let MarkerWidth = "markerWidth"
        let Mask = "mask"
        let MaskContentUnits = "maskContentUnits"
        let MaskUnits = "maskUnits"
        let Max = "max"
        let Min = "min"
        let Mode = "mode"
        let NumOctaves = "numOctaves"
        let Opacity = "opacity"
        let Operator = "operator"
        let Order = "order"
        let Overflow = "overflow"
        let PaintOrder = "paint-order"
        let PathLength = "pathLength"
        let PatternContentUnits = "patternContentUnits"
        let PatternTransform = "patternTransform"
        let PatternUnits = "patternUnits"
        let PointerEvents = "pointer-events"
        let Points = "points"
        let PointsAtX = "pointsAtX"
        let PointsAtY = "pointsAtY"
        let PointsAtZ = "pointsAtZ"
        let PreserveAlpha = "preserveAlpha"
        let PreserveAspectRatio = "preserveAspectRatio"
        let PrimitiveUnits = "primitiveUnits"
        let R = "r"
        let Radius = "radius"
        let RepeatCount = "repeatCount"
        let RepeatDur = "repeatDur"
        let RequiredFeatures = "requiredFeatures"
        let Restart = "restart"
        let Result = "result"
        let RX = "rx"
        let RY = "ry"
        let Scale = "scale"
        let Seed = "seed"
        let ShapeRendering = "shape-rendering"
        let SpecularConstant = "specularConstant"
        let SpecularExponent = "specularExponent"
        let StdDeviation = "stdDeviation"
        let StitchTiles = "stitchTiles"
        let StopColor = "stop-color"
        let StopOpacity = "stop-opacity"
        let Stroke = "stroke"
        let StrokeDashArray = "stroke-dasharray"
        let StrokeDashOffset = "stroke-dashoffset"
        let StrokeLineCap = "stroke-linecap"
        let StrokeLineJoin = "stroke-linejoin"
        let StrokeMiterLimit = "stroke-miterlimit"
        let StrokeOpacity = "stroke-opacity"
        let StrokeWidth = "stroke-width"
        let Style = "style"
        let SurfaceScale = "surfaceScale"
        let TargetX = "targetX"
        let TargetY = "targetY"
        let TextAnchor = "text-anchor"
        let TextDecoration = "text-decoration"
        let TextRendering = "text-rendering"
        let To = "to"
        let Transform = "transform"
        let Type = "type"
        let Values = "values"
        let ViewBox = "viewBox"
        let Visibility = "visibility"
        let Width = "width"
        let WordSpacing = "word-spacing"
        let WritingMode = "writing-mode"
        let X = "x"
        let X1 = "x1"
        let X2 = "x2"
        let XChannelSelector = "xChannelSelector"
        let Y = "y"
        let Y1 = "y1"
        let Y2 = "y2"
        let YChannelSelector = "yChannelSelector"
        let Z = "z"
        // </SVGA>

    // Shared vocabulary: currently maintained by hand (white-listing).
    // We don't want to dump Elem.Map etc for people who open this module.

    // <Common>
    let A atr ch = Elements.A atr ch
    let A0 ch = Elements.A [] ch
    let Del atr ch = Elements.Del atr ch
    let Del0 ch = Elements.Del [] ch
    let Div atr ch = Elements.Div atr ch
    let Div0 ch = Elements.Div [] ch
    let Form atr ch = Elements.Form atr ch
    let Form0 ch = Elements.Form [] ch
    let H1 atr ch = Elements.H1 atr ch
    let H10 ch = Elements.H1 [] ch
    let H2 atr ch = Elements.H2 atr ch
    let H20 ch = Elements.H2 [] ch
    let H3 atr ch = Elements.H3 atr ch
    let H30 ch = Elements.H3 [] ch
    let H4 atr ch = Elements.H4 atr ch
    let H40 ch = Elements.H4 [] ch
    let H5 atr ch = Elements.H5 atr ch
    let H50 ch = Elements.H5 [] ch
    let H6 atr ch = Elements.H6 atr ch
    let H60 ch = Elements.H6 [] ch
    let LI atr ch = Elements.LI atr ch
    let LI0 ch = Elements.LI [] ch
    let Label atr ch = Elements.Label atr ch
    let Label0 ch = Elements.Label [] ch
    let Nav atr ch = Elements.Nav atr ch
    let Nav0 ch = Elements.Nav [] ch
    let P atr ch = Elements.P atr ch
    let P0 ch = Elements.P [] ch
    let Span atr ch = Elements.Span atr ch
    let Span0 ch = Elements.Span [] ch
    let Table atr ch = Elements.Table atr ch
    let Table0 ch = Elements.Table [] ch
    let TBody atr ch = Elements.TBody atr ch
    let TBody0 ch = Elements.TBody [] ch
    let THead atr ch = Elements.THead atr ch
    let THead0 ch = Elements.THead [] ch
    let TR atr ch = Elements.TR atr ch
    let TR0 ch = Elements.TR [] ch
    let TD atr ch = Elements.TD atr ch
    let TD0 ch = Elements.TD [] ch
    let UL atr ch = Elements.UL atr ch
    let UL0 ch = Elements.UL [] ch
    let OL atr ch = Elements.OL atr ch
    let OL0 ch = Elements.OL [] ch
    // </Common>
