// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../ProvidedTypes.fsi"
      "../ProvidedTypes.fs"
      "../AssemblyReader.fs"
      "../AssemblyReaderReflection.fs"
      "../ProvidedTypesContext.fs"
      "../ProvidedTypesContextFunc.fs"
      "../AST.fs"
      "../Parsing.fs"
      "../Runtime.fs"
      "../RuntimeClient.fs"
      "../OldProvider.fs"
      "../TemplatingProvider.fs"
